//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Licenta.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pacient()
        {
            this.pacient_simptome = new HashSet<pacient_simptome>();
        }
    
        public int Id { get; set; }
        public string nume { get; set; }
        public string prenume { get; set; }
        public string sex { get; set; }
        public Nullable<System.DateTime> data_nastere { get; set; }
        public string adresa { get; set; }
        public string email { get; set; }
        public string oras { get; set; }
        public string judet { get; set; }
        public string alte_detalii { get; set; }
        public string comentarii { get; set; }
        public Nullable<System.DateTime> creat { get; set; }
        public string last_modified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pacient_simptome> pacient_simptome { get; set; }
    }
}
